"""empty message

Revision ID: 008fc213c107
Revises: 
Create Date: 2020-11-29 16:14:25.931550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008fc213c107'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('current_score', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
